In [34]:
import pandas as pd
from prediction.classify_predict import compute_implied_probability

In [35]:
classified_df = pd.read_csv('prediction/output/classified_predictions.csv')
classified_df.head()

,uri,cid,author_handle,author_did,text,created_at,indexed_at,langs,like_count,repost_count,reply_count,quote_count,source_query,query_team,is_predictive,predicted_party,confidence,reason,needs_review
0,at://did:plc:uja4msdr44t62szbfe5wzdu4/app.bsky...,bafyreig6dhq6jv6bv3ujpk7zt5fn6jxvof5o66tqo7mu2...,joelmarques84.bsky.social,did:plc:uja4msdr44t62szbfe5wzdu4,Hummmmm... How am I going to say this.... The ...,2026-07-06T21:27:00.894Z,2026-07-06T21:27:03.028Z,en,1,1,0,0,2028 election,macro_market,False,NaN,NaN,The post is discussing the midterms and their ...,False
1,at://did:plc:zy6nkkusnwgio57qkp7fhwuh/app.bsky...,bafyreif3lhtl3qpbgdbi3mnfezebcgnif5w2k4ic4fi2w...,bearlyfantasy.bsky.social,did:plc:zy6nkkusnwgio57qkp7fhwuh,Campaigns are starting to ramp up for the 2028...,2026-07-06T21:24:38.640Z,2026-07-06T21:24:38.926Z,en,1,0,2,0,2028 election,macro_market,False,NaN,NaN,The author is discussing their personal belief...,False
2,at://did:plc:buj3fjj6dar54jcdvvsp3m5n/app.bsky...,bafyreialjbalip74yzkfmtupow42k32r6mazzyvkm7fun...,sonnycohen.bsky.social,did:plc:buj3fjj6dar54jcdvvsp3m5n,The 2026 midterms are in 120 days; the 2028 pr...,2026-07-06T20:28:14.157Z,2026-07-06T20:28:13.029Z,en,0,0,0,0,2028 election,macro_market,False,NaN,NaN,The post does not mention any specific party o...,False
3,at://did:plc:rmrgs7t75mvedc2zbnvnv6og/app.bsky...,bafyreibzqfclchf4jliol3zwso6cfvf6stop4mlicsil7...,poppy1234567.bsky.social,did:plc:rmrgs7t75mvedc2zbnvnv6og,What is the impact of republicans buying domin...,2026-07-06T20:15:45.767Z,2026-07-06T20:15:46.837Z,en,0,0,0,0,2028 election,macro_market,False,NaN,NaN,The post is discussing various topics unrelate...,False
4,at://did:plc:6lpk72rqnczhh3f2ykm2nytl/app.bsky...,bafyreidhyid765zheq76uh5vww54aaze26akkoxr7j76x...,notelon.bsky.social,did:plc:6lpk72rqnczhh3f2ykm2nytl,If this is what they're going to do for a fuck...,2026-07-06T20:00:40.654Z,2026-07-06T20:00:40.621Z,en,2,0,0,0,2028 election,macro_market,False,NaN,NaN,The post expresses an opinion about who will w...,False

In [36]:
print(classified_df.shape)
print("Democrat's Posts: ", (classified_df['predicted_party'] == 'Democrat').sum())
print("Republican's Posts: ", (classified_df['predicted_party'] == 'Republican').sum())
print("Non-predictive Posts: ", (classified_df['predicted_party'].isnull()).sum())

(6038, 19)
Democrat's Posts:  14
Republican's Posts:  13
Non-predictive Posts:  6011

In [37]:
compute_implied_probability(classified_df)

--- Bluesky Implied Probability ---
  Democrat:    53.8%  (7 posts)
  Republican:  46.2%  (6 posts)
  Third Party: 0.0%  (0 posts)
  Total predictive posts: 13

{'Democrat': np.float64(0.5385),
 'Republican': np.float64(0.4615),
 'Third Party': np.float64(0.0)}

In [38]:
df = pd.read_csv('BLUESKY_POSTS_KXPRESPARTY_2028.csv')
df.head()

,uri,cid,author_handle,author_did,text,created_at,indexed_at,langs,like_count,repost_count,reply_count,quote_count,source_query,query_team
0,at://did:plc:rudwzj5uwhvocjdhltfuewmn/app.bsky...,bafyreif22oinsbq5ntxniinoic2dlow7rhyz7htehx65e...,colin25.bsky.social,did:plc:rudwzj5uwhvocjdhltfuewmn,Seemingly the republican party has suggested t...,2026-07-09T13:43:21.495Z,2026-07-09T13:43:21.330Z,en,0,0,0,0,Republican party,macro_market
1,at://did:plc:xtrlfckue4nevvszdzlqbmlz/app.bsky...,bafyreibpvmwqjg7x57jdtxcoehzi3ry567fka45yyzksg...,jomarie05.bsky.social,did:plc:xtrlfckue4nevvszdzlqbmlz,Great news. A house divided will never be unit...,2026-07-09T13:42:59.752Z,2026-07-09T13:43:01.324Z,en,1,0,0,0,Republican party,macro_market
2,at://did:plc:odu6ujihvuflnsw5zy4hog6h/app.bsky...,bafyreiepkftz5eb4bxwkhup5v33e7ed7eppljdhwe5f2w...,deltaowl.bsky.social,did:plc:odu6ujihvuflnsw5zy4hog6h,They're going to imbue his living soul into a ...,2026-07-09T13:42:27.090Z,2026-07-09T13:42:27.331Z,en,0,0,0,0,Republican party,macro_market
3,at://did:plc:nj7iog6v4yov2e7tctmwq6n3/app.bsky...,bafyreih633p2heamhodlidjlyj3js2oynr45dnoqxilqj...,kimoco.bsky.social,did:plc:nj7iog6v4yov2e7tctmwq6n3,"Heartbreaking yes, but also extremely RACIST. ...",2026-07-09T13:42:27.930Z,2026-07-09T13:42:29.722Z,en,0,0,0,0,Republican party,macro_market
4,at://did:plc:mejqjsugpcokug4wugy2wzk3/app.bsky...,bafyreibtdgdtuyk4q4iznrtgqy5vtwogcwnqiqw2jt3ox...,1granitodearena.bsky.social,did:plc:mejqjsugpcokug4wugy2wzk3,Retaking the agenda from Trump implies attacki...,2026-07-09T13:42:18.751Z,2026-07-09T13:42:20.628Z,en,0,0,0,0,Republican party,macro_market

In [39]:
compute_implied_probability(df)

KeyError: 'is_predictive'